version: "2"
services:

  mongoDB:
    image: mongo:3.0.7
    restart: always
    container_name: mongoDB
    hostname: containerMONGODB
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=senha@123
    ports:
    - "27017:27017"
    volumes:
    - /data_docker2/mongodata/mongovol:/data/db
    - /data_docker2/mongodata/mongoconfig:/data/configdb

volumes:
  mongovol:
  mongoconfig:
